import { nextJsConfig } from "@workspace/eslint-config/next-js"

/** @type {import("eslint").Linter.Config} */
export default [
  // Generated by fumadocs-mdx
  { ignores: [".source/**"] },
  ...nextJsConfig,
]
